# Get activated when pushing to the main branch

name: Deploy
on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    name: deployment to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Node for any Compression
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      
      - name: Install Dependencies
        run: npm install
        
        #Setup of Hugo and Caching of files
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Clean public directory
        run: rm -rf public
      
      
      - name: Cache Hugo Files
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: hugo --minify
        
        # Deployment to server. Secrets need to be entered via settings -> secrets in the repo. Change parameter accordingly.
        
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-avz --delete"
            SOURCE: "public/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: "~/html/"
